name: Deploy To Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, vglla-live]

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "vergola.github@knowdgeplus.net.au"
          git config --global user.name "kplus-vergola"
    
      - name: Deploy Application
        run: |
          cd C:/xampp/htdocs/VergolaLA

          git pull origin main
